HW 1
jpp2464

In [50]:
!pip install torch
import torch
import numpy as np
import pandas as pd
from torch import nn


[notice] A new release of pip available: 22.2.2 -> 23.0.1
[notice] To update, run: pip install --upgrade pip


1.1

In [26]:
x = torch.tensor([4,2], dtype=torch.float, requires_grad=True)
w = torch.tensor([2,1],dtype=torch.float)
b = torch.tensor(3,dtype=torch.float)
y = torch.matmul(w.T,x) + b

In [27]:
y.backward()

In [28]:
x.grad

tensor([2., 1.])

1.2

In [51]:
y_true = torch.tensor([0,1,1,0],dtype=torch.float)
y_pred = torch.tensor([0.1,0.95,1.10,0.2])

mse_model = torch.nn.MSELoss()(y_true,y_pred)

In [52]:
print(mse_model.item())

0.01562500186264515


1.3

In [115]:
x = torch.tensor([[0,0],[0,1],[1,0],[1,1]],dtype=torch.float)
w = torch.tensor([2,1],dtype=torch.float,requires_grad=True)
b = torch.tensor(3.0,requires_grad=True)

In [116]:
y_prediction = torch.sum(w*x,1)+b
y = torch.tensor([0,1,1,0],dtype=torch.float)


1.3 i 

In [117]:
mse_loss=torch.nn.MSELoss()(y,y_prediction)
print(mse_loss.item())

17.5


1.3 ii 

In [118]:
mse_loss.backward()
w.grad

tensor([5.0000, 4.5000])

In [119]:
b.grad

tensor(8.)

1.3 iii 
paper only 

w1 = 0, w2 = 0, w3 = 1/2

2.1

In [120]:
x = torch.tensor([1,-1,3,4,4], dtype=torch.float)
x = x1.unsqueeze(0)
x.shape

torch.Size([1, 1, 5])

In [121]:
convol1 = nn.Conv1d(in_channels=1, out_channels=1, kernel_size=2,bias=False)
convol1.weight.data=torch.tensor([1, 1],dtype=torch.float,requires_grad=True)
convol1.weight.data=convol1.weight.data.unsqueeze(0).unsqueeze(0)
convol1.weight.data

tensor([[[1., 1.]]])

In [122]:
output = convol1(x)
output

tensor([[[0., 2., 7., 8.]]], grad_fn=<ConvolutionBackward0>)

In [99]:
convol2 = nn.Conv1d(in_channels=1, out_channels=1, kernel_size=2, stride = 2, bias=False)
convol2.weight.data=torch.tensor([1, 1],dtype=torch.float,requires_grad=True)
convol2.weight.data=convol2.weight.data.unsqueeze(0).unsqueeze(0)
convol2.weight.data

tensor([[[1., 1.]]])

In [100]:
output_2 = convol2(x)
output_2

tensor([[[0., 7.]]], grad_fn=<ConvolutionBackward0>)

2.2

2.2i 

In [101]:
x22 = torch.tensor([[0.1,-0.6,0.4,0.8],[-0.4,0.3,0.9,0.2],[0.5,0.2,0.8,-0.7],[0.3,0.7,-0.4,0.1]])
x22 = x22.unsqueeze(0)
x22.shape

torch.Size([1, 4, 4])

In [105]:
conv22=nn.Conv2d(in_channels=1,out_channels=1,kernel_size=2,bias=False)
conv22.weight.data=torch.tensor([[1,0],[0,1]],dtype=torch.float)
conv22.weight.data=conv22.weight.data.unsqueeze(0).unsqueeze(0)
conv22.weight.data.shape

torch.Size([1, 1, 2, 2])

In [107]:
output_3 = conv22(x22)
output_3


tensor([[[ 0.4000,  0.3000,  0.6000],
         [-0.2000,  1.1000,  0.2000],
         [ 1.2000, -0.2000,  0.9000]]], grad_fn=<SqueezeBackward1>)

In [112]:
conv23 = nn.Conv2d(in_channels=1,out_channels=1,kernel_size=2,bias=False)
conv23.weight.data = torch.tensor([[0,1],[1,0]],dtype=torch.float)
conv23.weight.data = conv23.weight.data.unsqueeze(0).unsqueeze(0)
conv23.weight.data.shape

torch.Size([1, 1, 2, 2])

In [113]:
output_4 = cnn2d_2(x22)
output_4

tensor([[[-1.0000,  0.7000,  1.7000],
         [ 0.8000,  1.1000,  1.0000],
         [ 0.5000,  1.5000, -1.1000]]], grad_fn=<SqueezeBackward1>)

iv

In [111]:
max_pooling = nn.MaxPool2d(2, stride=1)
yy = max_pooling(x22)
yy

tensor([[[0.3000, 0.9000, 0.9000],
         [0.5000, 0.9000, 0.9000],
         [0.7000, 0.8000, 0.8000]]])